### ISSUE TITLE
ZCTA support?

### ISSUE THREAD

**Issue by thunter009** [cenpy-devs/cenpy#106]
Hi ! 

I'm looking to query Census data in a reliable way using python and evaluating cenpy vs datamade's census library. I'm wondering if there is support for ZCTAs? It seems like there should be when reading the docs but I'm running into errors when trying to set the level = 'ZCTA'. Any ideas?

**Comment by dfolch** [comment]
The following example will pull ZCTAs for the whole country from the 2010-2014 ACS.

```python
conn = cenpy.products.APIConnection("ACSDT5Y2014")
data = conn.query(["B01001_001E"], geo_unit = 'zip code tabulation area')
```

**Comment by thunter009** [comment]
Great thank you! I will test this out.
