### ISSUE TITLE
links on pypi are not resolving correctly

### ISSUE THREAD

**Issue by ljwolf** [cenpy-devs/cenpy#109]
Filed via private email, I've just been made aware that the links on pypi.org/project/cenpy are not redirecting correctly to nbviewer. Not sure why, since they're working on github.

**Comment by rluedde** [comment]
All five links at the top of the page work correctly. For that matter, all links on the page work correctly.

**Comment by jGaboardi** [comment]
> All five links at the top of the page work correctly. For that matter, all links on the page work correctly.

@rluedde Thanks for the update! I can also confirm, so closing for now. We can reopen if the issue crops up again.
