### ISSUE TITLE
APIConnection Explain uses depreciated ix

### ISSUE THREAD

**Issue by kyu21** [cenpy-devs/cenpy#110]
Using pandas>=1.0.0 removes Dataframe.ix and this causes APIConnection.explain to not run. 

https://github.com/cenpy-devs/cenpy/blob/d31530fbda0aed605b2d11516836384b29700b30/cenpy/remote.py#L136-L137

Any plans on updating this to accommodate for newer pandas versions? .loc should work here instead.

**Comment by ljwolf** [comment]
Yeah, the PR should be fast! Thank you for flagging this. There is no workaround at the moment for explain. I'll fix this and do a point release in the next week.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by ljwolf** [comment]
This should be addressed in version `1.0.0.post4`. Thank you!
