### ISSUE TITLE
Is it possible to filter QWI data during the query to avoid 400k limit?

### ISSUE THREAD

**Issue by asker4ik** [cenpy-devs/cenpy#118]
I am trying to work with QWI data using cenpy package. I am interested in filtering the 'industry' variable to just request only NAICS 3-digit codes and avoid two and especially four-digit ones.  Below is my code. It successfully downloads the data, but I can't add any other variables because it straight away violates the limit. Would be great to be able to filter values upfront. 

```python
import pandas as pd
import cenpy as cen

#Call list of available datasets, verbose = True to include dataset title
datasets = list(cen.explorer.available(verbose=True).items())
#Convert dictionary to dataframe
datasets = pd.DataFrame(datasets, columns = ['code', 'dataset name'])


qwi_connection = cen.remote.APIConnection('QWISA')

#Specify all counties
g_unit = 'county:061'
#Start with one state (chosen arbitrarily) 
g_filter = {'state': '36'}
#Specify time period
time = 'from 2000-Q1 to 2000-Q2'

#Uses .varslike to pull in all indicator names
emp = qwi_connection.varslike('Emp')    # Employment - just one variable Emp
emp = emp.reset_index()
emp = emp[emp['index'] == 'Emp']
emp = emp.set_index('index')

edu = qwi_connection.varslike('education')    # education
age = qwi_connection.varslike('agegrp')

earns = qwi_connection.varslike('EarnS')  # Earning
earns = earns.reset_index()
earns = earns[earns['index'] == 'EarnS']
earns = earns.set_index('index')

empend = qwi_connection.varslike('EmpEnd')
empend = empend.drop('sEmpEnd', axis = 0)

eth = qwi_connection.varslike('ethnicity')

firm = qwi_connection.varslike('firm')
firm = firm.drop('firmage', axis = 0)
firm

sex = qwi_connection.varslike('sex')

payroll = qwi_connection.varslike('Payroll') # Payroll
payroll = payroll.drop('sPayroll', axis = 0)

ind = qwi_connection.varslike('industry') 

df = pd.concat([age, emp, earns, payroll, ind, empend, sex])

df = df.reset_index()

df.columns = ['columns', 'label', 'concept', 'predicateType', 'group', 'limit',
       'predicateOnly', 'datetime', 'required']

col_list = df['columns']

########## Test run of the QWI API
master = qwi_connection.query(cols = col_list, time = time,
                              geo_filter = g_filter,
                              geo_unit = g_unit,
                              apikey = 'YourKey')  #you need a census API key to be able to run this part
```

**Comment by dfolch** [comment]
One solution is to add `industry=naics_code` to the query. In this example it would be...

```python
master = qwi_connection.query(cols = col_list, time = time,
                              geo_filter = g_filter,
                              geo_unit = g_unit,
                              industry = '11')
```

cenpy will automatically pass on predicates to the API. The [docs for this case are here](https://www.census.gov/data/developers/data-sets/qwi.html#industry).

Note: predicates are not always consistent between databases. [This example](https://github.com/cenpy-devs/cenpy/issues/12#issuecomment-509282410) shows that the predicate to select by NAICS for County Business Patterns is different.

**Comment by asker4ik** [comment]
> One solution is to add `industry=naics_code` to the query. In this example it would be...
> 
> ```python
> master = qwi_connection.query(cols = col_list, time = time,
>                               geo_filter = g_filter,
>                               geo_unit = g_unit,
>                               industry = '11')
> ```
> 
> cenpy will automatically pass on predicates to the API. The [docs for this case are here](https://www.census.gov/data/developers/data-sets/qwi.html#industry).
> 
> Note: predicates are not always consistent between databases. [This example](https://github.com/cenpy-devs/cenpy/issues/12#issuecomment-509282410) shows that the predicate to select by NAICS for County Business Patterns is different.

Thank you very much! It worked for me. And I assume there is no functionality to use a filter for a predicate? Like for example if I needed to filter by multiple NAICs codes? Not that I can't write a loop, but does not hurt to ask.

**Comment by ljwolf** [comment]
Try using `industry='11&12'`, like you would in the API call directly

**Comment by asker4ik** [comment]
> Try using `industry='11&12'`, like you would in the API call directly

This is absolutely perfect! Thank you!
