### ISSUE TITLE
extend CI?

### ISSUE THREAD

**Issue by jGaboardi** [cenpy-devs/cenpy#135]
@ljwolf @ronnie-llamado How do we feel about extending CI to other platforms and Python versions? If it is not desired, that's all good and we can close this issue. If it is, check off what you would like and I will see about implementing them.

* OS
  * [x] Linux (current)
  * [x] macOS
  * [x] Windows
* Python
  * [ ] ~~3.5~~ [`rtree` problem](https://github.com/cenpy-devs/cenpy/runs/2441522597?check_suite_focus=true#step:3:53)
  * [x] 3.6 (current)
  * [x] 3.7
  * [x] 3.8
  * [x] 3.9

**Comment by ronnie-llamado** [comment]
I'm all for it, but I'll defer to @ljwolf on the selection of platforms and python versions.

**Comment by ljwolf** [comment]
Sure! I just haven’t touched the CI in a very long time, so I’m game for whatever enhancements folks know how to make!

From: ronnie-llamado ***@***.***>
Date: Monday, 26 April 2021 at 18:30
To: cenpy-devs/cenpy ***@***.***>
Cc: Levi John Wolf ***@***.***>, Mention ***@***.***>
Subject: Re: [cenpy-devs/cenpy] extend CI? (#135)

I'm all for it, but I'll defer to @ljwolf<https://github.com/ljwolf> on the selection of platforms and python versions.

**Comment by jGaboardi** [comment]
@ljwolf and @ronnie-llamado OK, sounds good!
