### ISSUE TITLE
IndexError in ACS._from_name

### ISSUE THREAD

**Issue by dbragdon1** [cenpy-devs/cenpy#146]
Hello, I believe I caught an error in the method for catching invalid level types in the _from_name method in the ACS class. 

Starting in line 702 in `products.py` in the `_from_name` function:

```python
if level not in self._layer_lookup.keys():
            raise NotImplementedError(
                "Only levels {} are supported. You provided {}."
                "Try picking the state containing that level,"
                " and then selecting from that data after it is"
                " fetched".format(level)
            )
```

As far as I can tell, level is supposed to be a single string, and yet this formatting requires two arguments to properly work. Thus when entering an invalid level type, `IndexError` is thrown:

```
python3.7/site-packages/cenpy/products.py", line 707, in _from_name
    " fetched".format(level)
IndexError: tuple index out of range
```

**Comment by ronnie-llamado** [comment]
Good catch. It looks like this was addressed in #119, but still needs to be merged in.
