### ISSUE TITLE
Running example notebook requires descartes package

### ISSUE THREAD

**Issue by MaxGhenis** [cenpy-devs/cenpy#84]
The [product-api notebook](https://nbviewer.jupyter.org/github/cenpy-devs/cenpy/blob/master/notebooks/product-api.ipynb) breaks when plotting in cell 3 unless `descartes` is installed. Should this be a dep of cenpy on conda? Running `conda install descartes` resolved it.

**Comment by knaaptime** [comment]
descartes is an optional dependency of geopandas (thats necessary to do any plotting). So any time users want to plot with geopandas (cenpy or not), they will need to have descartes available. 

In this specific case, plotting is convenient, but it's not strictly necessary for cenpy, so i dont think a hard dependency on descartes is appropriate

**Comment by ljwolf** [comment]
I agree; this is an issue with `geopandas` not grabbing `descartes` by default for plotting purposes. 
I don't think it's a good idea to add `descartes` to `cenpy`. 

I can raise this up w/ geopandas devs... last I recall there was discussion of [just vendoring the package](https://github.com/geopandas/geopandas/issues/1039) but I can't recall where we came down on that.

**Comment by MaxGhenis** [comment]
Makes sense, if you're editing the notebook at some point this could be useful to point out, or maybe in the documentation.
